### PR TITLE
Remove redundant troubleshooting link

### PR DESCRIPTION
**Pull request by anik120**
A header for troubleshooting already exists

### CODE REVIEW

**Comment by Bowenislandsong** [comment]
I think @dmesser might be referring to fail to install OLM? If the intent is still troubleshooting for operator install failure which is the same as https://github.com/operator-framework/olm-book/blob/master/docs/troubleshooting.md, then you might want to delete the Jira card too. 

/cc @dmesser

**Comment by anik120** [comment]
> I think @dmesser might be referring to fail to install OLM? 

@Bowenislandsong could you explain more? I'm not sure I got you there. 

>If the intent is still troubleshooting for operator install failure which is the same as https://github.com/operator-framework/olm-book/blob/master/docs/troubleshooting.md, then you might want to delete the Jira card too.

According to me Jira tickets are not relevant to PRs :p 
But you do bring up a good point. I've noticed there are some redundant stories related to docs that we should clean up.

**Comment by Bowenislandsong** [comment]
> > I think @dmesser might be referring to fail to install OLM?
> 
> @Bowenislandsong could you explain more? I'm not sure I got you there.

That troubleshoot doc helps with installing operator failures. I wonder if this one is about troubleshooting for installing OLM? I don't really know the intent there. Similar things exist for other stories, I think we should bring it up in a meeting before deleting them. 

> > If the intent is still troubleshooting for operator install failure which is the same as https://github.com/operator-framework/olm-book/blob/master/docs/troubleshooting.md, then you might want to delete the Jira card too.
> 
> According to me Jira tickets are not relevant to PRs :p
I think out doc Jira card matches every topic here.
> But you do bring up a good point. I've noticed there are some redundant stories related to docs that we should clean up.
:+1:

**Comment by anik120** [comment]
> That troubleshoot doc helps with installing operator failures. I wonder if this one is about troubleshooting for installing OLM? I don't really know the intent there. Similar things exist for other stories, I think we should bring it up in a meeting before deleting them.

@Bowenislandsong my point is that there a [section](https://operator-framework.github.io/olm-book/#troubleshooting) that has both the docs: troubleshooting for installing OLM and troubleshooting operator installation with OLM. This PR is just removing the troubleshooting for operator installation with OLM under the "Basic use cases" section, which I believe is a duplicate and is redundant.

**Pull request merged**
